### ISSUE TITLE
Exception: 教务系统出现了问题啦！返回状态码：200

### ISSUE THREAD

**Issue by Obozha** [yurhett/Fuck_HENUDC#1]
大佬，这种情况怎么样才能work

**Comment by yurhett** [comment]
你好，这套源码目前是可用的，如果您不明白问题出在哪里您可以克隆到您的机器上并使用 pip install -r requirements.txt配置环境 在本地运行可以将config.yml的debug设置为true，您将通过调试获得错误的更多信息。如果您对配置教程或其它的内容有疑问，欢迎提问。
