### ISSUE TITLE
无法登录HENU教务系统  错误码：200

### ISSUE THREAD

**Issue by ZixuanWang1210** [yurhett/Fuck_HENUDC#5]

**Comment by yurhett** [comment]
你好 教务系统现在正常登陆 但是这套代码已经没法签到了 目前已经修改修复 由于有风险被检测 故暂未更新 如果需要代码 你可以留下邮箱

**Comment by ZixuanWang1210** [comment]
学长好，PR里的代码好像可以获得cookies了。但是在查询未签到的任务（也就是调用auto_sign的时候）没有数据返回。我的邮箱：wangzixuan1210@gmail.com。希望能学习一下学长代码。
